#!/bin/bash

echo "make apps"
make apps

tests=("SimpleSequential" "DeviceMemcpy" "SimpleTileLoadStore" "FifoLoad" "ParFifoLoad" "FifoLoadStore" "SimpleReduce" "Niter" "SimpleFold" "Memcpy2D" "BlockReduce1D" "UnalignedLd" "BlockReduce2D" "ScatterGather" "InOutArg" "MultiplexedWriteTest" "BubbledWriteTest" "SequentialWrites" "ChangingCtrMax" "FifoPushPop")


for test in "${tests[@]}"
do : 
  echo "spatial $test"
  spatial $test
done
