// Computer_System_mm_interconnect_5.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 16.1 196

`timescale 1 ps / 1 ps
module Computer_System_mm_interconnect_5 (
		input  wire        System_PLL_sys_clk_clk,                                   //                                 System_PLL_sys_clk.clk
		input  wire        Expansion_JP2_reset_reset_bridge_in_reset_reset,          //          Expansion_JP2_reset_reset_bridge_in_reset.reset
		input  wire        Video_In_Subsystem_sys_reset_reset_bridge_in_reset_reset, // Video_In_Subsystem_sys_reset_reset_bridge_in_reset.reset
		input  wire [3:0]  Video_In_Subsystem_top_io_gpi2_streamin_address,          //            Video_In_Subsystem_top_io_gpi2_streamin.address
		input  wire        Video_In_Subsystem_top_io_gpi2_streamin_chipselect,       //                                                   .chipselect
		input  wire        Video_In_Subsystem_top_io_gpi2_streamin_read,             //                                                   .read
		output wire [31:0] Video_In_Subsystem_top_io_gpi2_streamin_readdata,         //                                                   .readdata
		input  wire [3:0]  Video_In_Subsystem_top_io_gpo2_streamout_address,         //           Video_In_Subsystem_top_io_gpo2_streamout.address
		input  wire        Video_In_Subsystem_top_io_gpo2_streamout_chipselect,      //                                                   .chipselect
		input  wire        Video_In_Subsystem_top_io_gpo2_streamout_write,           //                                                   .write
		input  wire [31:0] Video_In_Subsystem_top_io_gpo2_streamout_writedata,       //                                                   .writedata
		output wire [1:0]  Expansion_JP2_s1_address,                                 //                                   Expansion_JP2_s1.address
		output wire        Expansion_JP2_s1_write,                                   //                                                   .write
		input  wire [31:0] Expansion_JP2_s1_readdata,                                //                                                   .readdata
		output wire [31:0] Expansion_JP2_s1_writedata,                               //                                                   .writedata
		output wire        Expansion_JP2_s1_chipselect                               //                                                   .chipselect
	);

	wire         video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_waitrequest;    // Video_In_Subsystem_top_io_gpi2_streamin_agent:av_waitrequest -> Video_In_Subsystem_top_io_gpi2_streamin_translator:uav_waitrequest
	wire  [31:0] video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_readdata;       // Video_In_Subsystem_top_io_gpi2_streamin_agent:av_readdata -> Video_In_Subsystem_top_io_gpi2_streamin_translator:uav_readdata
	wire         video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_debugaccess;    // Video_In_Subsystem_top_io_gpi2_streamin_translator:uav_debugaccess -> Video_In_Subsystem_top_io_gpi2_streamin_agent:av_debugaccess
	wire   [3:0] video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_address;        // Video_In_Subsystem_top_io_gpi2_streamin_translator:uav_address -> Video_In_Subsystem_top_io_gpi2_streamin_agent:av_address
	wire         video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_read;           // Video_In_Subsystem_top_io_gpi2_streamin_translator:uav_read -> Video_In_Subsystem_top_io_gpi2_streamin_agent:av_read
	wire   [3:0] video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_byteenable;     // Video_In_Subsystem_top_io_gpi2_streamin_translator:uav_byteenable -> Video_In_Subsystem_top_io_gpi2_streamin_agent:av_byteenable
	wire         video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_readdatavalid;  // Video_In_Subsystem_top_io_gpi2_streamin_agent:av_readdatavalid -> Video_In_Subsystem_top_io_gpi2_streamin_translator:uav_readdatavalid
	wire         video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_lock;           // Video_In_Subsystem_top_io_gpi2_streamin_translator:uav_lock -> Video_In_Subsystem_top_io_gpi2_streamin_agent:av_lock
	wire         video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_write;          // Video_In_Subsystem_top_io_gpi2_streamin_translator:uav_write -> Video_In_Subsystem_top_io_gpi2_streamin_agent:av_write
	wire  [31:0] video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_writedata;      // Video_In_Subsystem_top_io_gpi2_streamin_translator:uav_writedata -> Video_In_Subsystem_top_io_gpi2_streamin_agent:av_writedata
	wire   [2:0] video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_burstcount;     // Video_In_Subsystem_top_io_gpi2_streamin_translator:uav_burstcount -> Video_In_Subsystem_top_io_gpi2_streamin_agent:av_burstcount
	wire         rsp_mux_src_valid;                                                                           // rsp_mux:src_valid -> Video_In_Subsystem_top_io_gpi2_streamin_agent:rp_valid
	wire  [73:0] rsp_mux_src_data;                                                                            // rsp_mux:src_data -> Video_In_Subsystem_top_io_gpi2_streamin_agent:rp_data
	wire         rsp_mux_src_ready;                                                                           // Video_In_Subsystem_top_io_gpi2_streamin_agent:rp_ready -> rsp_mux:src_ready
	wire   [1:0] rsp_mux_src_channel;                                                                         // rsp_mux:src_channel -> Video_In_Subsystem_top_io_gpi2_streamin_agent:rp_channel
	wire         rsp_mux_src_startofpacket;                                                                   // rsp_mux:src_startofpacket -> Video_In_Subsystem_top_io_gpi2_streamin_agent:rp_startofpacket
	wire         rsp_mux_src_endofpacket;                                                                     // rsp_mux:src_endofpacket -> Video_In_Subsystem_top_io_gpi2_streamin_agent:rp_endofpacket
	wire         video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_waitrequest;   // Video_In_Subsystem_top_io_gpo2_streamout_agent:av_waitrequest -> Video_In_Subsystem_top_io_gpo2_streamout_translator:uav_waitrequest
	wire  [31:0] video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_readdata;      // Video_In_Subsystem_top_io_gpo2_streamout_agent:av_readdata -> Video_In_Subsystem_top_io_gpo2_streamout_translator:uav_readdata
	wire         video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_debugaccess;   // Video_In_Subsystem_top_io_gpo2_streamout_translator:uav_debugaccess -> Video_In_Subsystem_top_io_gpo2_streamout_agent:av_debugaccess
	wire   [3:0] video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_address;       // Video_In_Subsystem_top_io_gpo2_streamout_translator:uav_address -> Video_In_Subsystem_top_io_gpo2_streamout_agent:av_address
	wire         video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_read;          // Video_In_Subsystem_top_io_gpo2_streamout_translator:uav_read -> Video_In_Subsystem_top_io_gpo2_streamout_agent:av_read
	wire   [3:0] video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_byteenable;    // Video_In_Subsystem_top_io_gpo2_streamout_translator:uav_byteenable -> Video_In_Subsystem_top_io_gpo2_streamout_agent:av_byteenable
	wire         video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_readdatavalid; // Video_In_Subsystem_top_io_gpo2_streamout_agent:av_readdatavalid -> Video_In_Subsystem_top_io_gpo2_streamout_translator:uav_readdatavalid
	wire         video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_lock;          // Video_In_Subsystem_top_io_gpo2_streamout_translator:uav_lock -> Video_In_Subsystem_top_io_gpo2_streamout_agent:av_lock
	wire         video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_write;         // Video_In_Subsystem_top_io_gpo2_streamout_translator:uav_write -> Video_In_Subsystem_top_io_gpo2_streamout_agent:av_write
	wire  [31:0] video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_writedata;     // Video_In_Subsystem_top_io_gpo2_streamout_translator:uav_writedata -> Video_In_Subsystem_top_io_gpo2_streamout_agent:av_writedata
	wire   [2:0] video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_burstcount;    // Video_In_Subsystem_top_io_gpo2_streamout_translator:uav_burstcount -> Video_In_Subsystem_top_io_gpo2_streamout_agent:av_burstcount
	wire         rsp_mux_001_src_valid;                                                                       // rsp_mux_001:src_valid -> Video_In_Subsystem_top_io_gpo2_streamout_agent:rp_valid
	wire  [73:0] rsp_mux_001_src_data;                                                                        // rsp_mux_001:src_data -> Video_In_Subsystem_top_io_gpo2_streamout_agent:rp_data
	wire         rsp_mux_001_src_ready;                                                                       // Video_In_Subsystem_top_io_gpo2_streamout_agent:rp_ready -> rsp_mux_001:src_ready
	wire   [1:0] rsp_mux_001_src_channel;                                                                     // rsp_mux_001:src_channel -> Video_In_Subsystem_top_io_gpo2_streamout_agent:rp_channel
	wire         rsp_mux_001_src_startofpacket;                                                               // rsp_mux_001:src_startofpacket -> Video_In_Subsystem_top_io_gpo2_streamout_agent:rp_startofpacket
	wire         rsp_mux_001_src_endofpacket;                                                                 // rsp_mux_001:src_endofpacket -> Video_In_Subsystem_top_io_gpo2_streamout_agent:rp_endofpacket
	wire  [31:0] expansion_jp2_s1_agent_m0_readdata;                                                          // Expansion_JP2_s1_translator:uav_readdata -> Expansion_JP2_s1_agent:m0_readdata
	wire         expansion_jp2_s1_agent_m0_waitrequest;                                                       // Expansion_JP2_s1_translator:uav_waitrequest -> Expansion_JP2_s1_agent:m0_waitrequest
	wire         expansion_jp2_s1_agent_m0_debugaccess;                                                       // Expansion_JP2_s1_agent:m0_debugaccess -> Expansion_JP2_s1_translator:uav_debugaccess
	wire   [3:0] expansion_jp2_s1_agent_m0_address;                                                           // Expansion_JP2_s1_agent:m0_address -> Expansion_JP2_s1_translator:uav_address
	wire   [3:0] expansion_jp2_s1_agent_m0_byteenable;                                                        // Expansion_JP2_s1_agent:m0_byteenable -> Expansion_JP2_s1_translator:uav_byteenable
	wire         expansion_jp2_s1_agent_m0_read;                                                              // Expansion_JP2_s1_agent:m0_read -> Expansion_JP2_s1_translator:uav_read
	wire         expansion_jp2_s1_agent_m0_readdatavalid;                                                     // Expansion_JP2_s1_translator:uav_readdatavalid -> Expansion_JP2_s1_agent:m0_readdatavalid
	wire         expansion_jp2_s1_agent_m0_lock;                                                              // Expansion_JP2_s1_agent:m0_lock -> Expansion_JP2_s1_translator:uav_lock
	wire  [31:0] expansion_jp2_s1_agent_m0_writedata;                                                         // Expansion_JP2_s1_agent:m0_writedata -> Expansion_JP2_s1_translator:uav_writedata
	wire         expansion_jp2_s1_agent_m0_write;                                                             // Expansion_JP2_s1_agent:m0_write -> Expansion_JP2_s1_translator:uav_write
	wire   [2:0] expansion_jp2_s1_agent_m0_burstcount;                                                        // Expansion_JP2_s1_agent:m0_burstcount -> Expansion_JP2_s1_translator:uav_burstcount
	wire         expansion_jp2_s1_agent_rf_source_valid;                                                      // Expansion_JP2_s1_agent:rf_source_valid -> Expansion_JP2_s1_agent_rsp_fifo:in_valid
	wire  [74:0] expansion_jp2_s1_agent_rf_source_data;                                                       // Expansion_JP2_s1_agent:rf_source_data -> Expansion_JP2_s1_agent_rsp_fifo:in_data
	wire         expansion_jp2_s1_agent_rf_source_ready;                                                      // Expansion_JP2_s1_agent_rsp_fifo:in_ready -> Expansion_JP2_s1_agent:rf_source_ready
	wire         expansion_jp2_s1_agent_rf_source_startofpacket;                                              // Expansion_JP2_s1_agent:rf_source_startofpacket -> Expansion_JP2_s1_agent_rsp_fifo:in_startofpacket
	wire         expansion_jp2_s1_agent_rf_source_endofpacket;                                                // Expansion_JP2_s1_agent:rf_source_endofpacket -> Expansion_JP2_s1_agent_rsp_fifo:in_endofpacket
	wire         expansion_jp2_s1_agent_rsp_fifo_out_valid;                                                   // Expansion_JP2_s1_agent_rsp_fifo:out_valid -> Expansion_JP2_s1_agent:rf_sink_valid
	wire  [74:0] expansion_jp2_s1_agent_rsp_fifo_out_data;                                                    // Expansion_JP2_s1_agent_rsp_fifo:out_data -> Expansion_JP2_s1_agent:rf_sink_data
	wire         expansion_jp2_s1_agent_rsp_fifo_out_ready;                                                   // Expansion_JP2_s1_agent:rf_sink_ready -> Expansion_JP2_s1_agent_rsp_fifo:out_ready
	wire         expansion_jp2_s1_agent_rsp_fifo_out_startofpacket;                                           // Expansion_JP2_s1_agent_rsp_fifo:out_startofpacket -> Expansion_JP2_s1_agent:rf_sink_startofpacket
	wire         expansion_jp2_s1_agent_rsp_fifo_out_endofpacket;                                             // Expansion_JP2_s1_agent_rsp_fifo:out_endofpacket -> Expansion_JP2_s1_agent:rf_sink_endofpacket
	wire         cmd_mux_src_valid;                                                                           // cmd_mux:src_valid -> Expansion_JP2_s1_agent:cp_valid
	wire  [73:0] cmd_mux_src_data;                                                                            // cmd_mux:src_data -> Expansion_JP2_s1_agent:cp_data
	wire         cmd_mux_src_ready;                                                                           // Expansion_JP2_s1_agent:cp_ready -> cmd_mux:src_ready
	wire   [1:0] cmd_mux_src_channel;                                                                         // cmd_mux:src_channel -> Expansion_JP2_s1_agent:cp_channel
	wire         cmd_mux_src_startofpacket;                                                                   // cmd_mux:src_startofpacket -> Expansion_JP2_s1_agent:cp_startofpacket
	wire         cmd_mux_src_endofpacket;                                                                     // cmd_mux:src_endofpacket -> Expansion_JP2_s1_agent:cp_endofpacket
	wire         video_in_subsystem_top_io_gpi2_streamin_agent_cp_valid;                                      // Video_In_Subsystem_top_io_gpi2_streamin_agent:cp_valid -> router:sink_valid
	wire  [73:0] video_in_subsystem_top_io_gpi2_streamin_agent_cp_data;                                       // Video_In_Subsystem_top_io_gpi2_streamin_agent:cp_data -> router:sink_data
	wire         video_in_subsystem_top_io_gpi2_streamin_agent_cp_ready;                                      // router:sink_ready -> Video_In_Subsystem_top_io_gpi2_streamin_agent:cp_ready
	wire         video_in_subsystem_top_io_gpi2_streamin_agent_cp_startofpacket;                              // Video_In_Subsystem_top_io_gpi2_streamin_agent:cp_startofpacket -> router:sink_startofpacket
	wire         video_in_subsystem_top_io_gpi2_streamin_agent_cp_endofpacket;                                // Video_In_Subsystem_top_io_gpi2_streamin_agent:cp_endofpacket -> router:sink_endofpacket
	wire         router_src_valid;                                                                            // router:src_valid -> cmd_demux:sink_valid
	wire  [73:0] router_src_data;                                                                             // router:src_data -> cmd_demux:sink_data
	wire         router_src_ready;                                                                            // cmd_demux:sink_ready -> router:src_ready
	wire   [1:0] router_src_channel;                                                                          // router:src_channel -> cmd_demux:sink_channel
	wire         router_src_startofpacket;                                                                    // router:src_startofpacket -> cmd_demux:sink_startofpacket
	wire         router_src_endofpacket;                                                                      // router:src_endofpacket -> cmd_demux:sink_endofpacket
	wire         video_in_subsystem_top_io_gpo2_streamout_agent_cp_valid;                                     // Video_In_Subsystem_top_io_gpo2_streamout_agent:cp_valid -> router_001:sink_valid
	wire  [73:0] video_in_subsystem_top_io_gpo2_streamout_agent_cp_data;                                      // Video_In_Subsystem_top_io_gpo2_streamout_agent:cp_data -> router_001:sink_data
	wire         video_in_subsystem_top_io_gpo2_streamout_agent_cp_ready;                                     // router_001:sink_ready -> Video_In_Subsystem_top_io_gpo2_streamout_agent:cp_ready
	wire         video_in_subsystem_top_io_gpo2_streamout_agent_cp_startofpacket;                             // Video_In_Subsystem_top_io_gpo2_streamout_agent:cp_startofpacket -> router_001:sink_startofpacket
	wire         video_in_subsystem_top_io_gpo2_streamout_agent_cp_endofpacket;                               // Video_In_Subsystem_top_io_gpo2_streamout_agent:cp_endofpacket -> router_001:sink_endofpacket
	wire         router_001_src_valid;                                                                        // router_001:src_valid -> cmd_demux_001:sink_valid
	wire  [73:0] router_001_src_data;                                                                         // router_001:src_data -> cmd_demux_001:sink_data
	wire         router_001_src_ready;                                                                        // cmd_demux_001:sink_ready -> router_001:src_ready
	wire   [1:0] router_001_src_channel;                                                                      // router_001:src_channel -> cmd_demux_001:sink_channel
	wire         router_001_src_startofpacket;                                                                // router_001:src_startofpacket -> cmd_demux_001:sink_startofpacket
	wire         router_001_src_endofpacket;                                                                  // router_001:src_endofpacket -> cmd_demux_001:sink_endofpacket
	wire         expansion_jp2_s1_agent_rp_valid;                                                             // Expansion_JP2_s1_agent:rp_valid -> router_002:sink_valid
	wire  [73:0] expansion_jp2_s1_agent_rp_data;                                                              // Expansion_JP2_s1_agent:rp_data -> router_002:sink_data
	wire         expansion_jp2_s1_agent_rp_ready;                                                             // router_002:sink_ready -> Expansion_JP2_s1_agent:rp_ready
	wire         expansion_jp2_s1_agent_rp_startofpacket;                                                     // Expansion_JP2_s1_agent:rp_startofpacket -> router_002:sink_startofpacket
	wire         expansion_jp2_s1_agent_rp_endofpacket;                                                       // Expansion_JP2_s1_agent:rp_endofpacket -> router_002:sink_endofpacket
	wire         router_002_src_valid;                                                                        // router_002:src_valid -> rsp_demux:sink_valid
	wire  [73:0] router_002_src_data;                                                                         // router_002:src_data -> rsp_demux:sink_data
	wire         router_002_src_ready;                                                                        // rsp_demux:sink_ready -> router_002:src_ready
	wire   [1:0] router_002_src_channel;                                                                      // router_002:src_channel -> rsp_demux:sink_channel
	wire         router_002_src_startofpacket;                                                                // router_002:src_startofpacket -> rsp_demux:sink_startofpacket
	wire         router_002_src_endofpacket;                                                                  // router_002:src_endofpacket -> rsp_demux:sink_endofpacket
	wire         cmd_demux_src0_valid;                                                                        // cmd_demux:src0_valid -> cmd_mux:sink0_valid
	wire  [73:0] cmd_demux_src0_data;                                                                         // cmd_demux:src0_data -> cmd_mux:sink0_data
	wire         cmd_demux_src0_ready;                                                                        // cmd_mux:sink0_ready -> cmd_demux:src0_ready
	wire   [1:0] cmd_demux_src0_channel;                                                                      // cmd_demux:src0_channel -> cmd_mux:sink0_channel
	wire         cmd_demux_src0_startofpacket;                                                                // cmd_demux:src0_startofpacket -> cmd_mux:sink0_startofpacket
	wire         cmd_demux_src0_endofpacket;                                                                  // cmd_demux:src0_endofpacket -> cmd_mux:sink0_endofpacket
	wire         cmd_demux_001_src0_valid;                                                                    // cmd_demux_001:src0_valid -> cmd_mux:sink1_valid
	wire  [73:0] cmd_demux_001_src0_data;                                                                     // cmd_demux_001:src0_data -> cmd_mux:sink1_data
	wire         cmd_demux_001_src0_ready;                                                                    // cmd_mux:sink1_ready -> cmd_demux_001:src0_ready
	wire   [1:0] cmd_demux_001_src0_channel;                                                                  // cmd_demux_001:src0_channel -> cmd_mux:sink1_channel
	wire         cmd_demux_001_src0_startofpacket;                                                            // cmd_demux_001:src0_startofpacket -> cmd_mux:sink1_startofpacket
	wire         cmd_demux_001_src0_endofpacket;                                                              // cmd_demux_001:src0_endofpacket -> cmd_mux:sink1_endofpacket
	wire         rsp_demux_src0_valid;                                                                        // rsp_demux:src0_valid -> rsp_mux:sink0_valid
	wire  [73:0] rsp_demux_src0_data;                                                                         // rsp_demux:src0_data -> rsp_mux:sink0_data
	wire         rsp_demux_src0_ready;                                                                        // rsp_mux:sink0_ready -> rsp_demux:src0_ready
	wire   [1:0] rsp_demux_src0_channel;                                                                      // rsp_demux:src0_channel -> rsp_mux:sink0_channel
	wire         rsp_demux_src0_startofpacket;                                                                // rsp_demux:src0_startofpacket -> rsp_mux:sink0_startofpacket
	wire         rsp_demux_src0_endofpacket;                                                                  // rsp_demux:src0_endofpacket -> rsp_mux:sink0_endofpacket
	wire         rsp_demux_src1_valid;                                                                        // rsp_demux:src1_valid -> rsp_mux_001:sink0_valid
	wire  [73:0] rsp_demux_src1_data;                                                                         // rsp_demux:src1_data -> rsp_mux_001:sink0_data
	wire         rsp_demux_src1_ready;                                                                        // rsp_mux_001:sink0_ready -> rsp_demux:src1_ready
	wire   [1:0] rsp_demux_src1_channel;                                                                      // rsp_demux:src1_channel -> rsp_mux_001:sink0_channel
	wire         rsp_demux_src1_startofpacket;                                                                // rsp_demux:src1_startofpacket -> rsp_mux_001:sink0_startofpacket
	wire         rsp_demux_src1_endofpacket;                                                                  // rsp_demux:src1_endofpacket -> rsp_mux_001:sink0_endofpacket
	wire         expansion_jp2_s1_agent_rdata_fifo_src_valid;                                                 // Expansion_JP2_s1_agent:rdata_fifo_src_valid -> avalon_st_adapter:in_0_valid
	wire  [33:0] expansion_jp2_s1_agent_rdata_fifo_src_data;                                                  // Expansion_JP2_s1_agent:rdata_fifo_src_data -> avalon_st_adapter:in_0_data
	wire         expansion_jp2_s1_agent_rdata_fifo_src_ready;                                                 // avalon_st_adapter:in_0_ready -> Expansion_JP2_s1_agent:rdata_fifo_src_ready
	wire         avalon_st_adapter_out_0_valid;                                                               // avalon_st_adapter:out_0_valid -> Expansion_JP2_s1_agent:rdata_fifo_sink_valid
	wire  [33:0] avalon_st_adapter_out_0_data;                                                                // avalon_st_adapter:out_0_data -> Expansion_JP2_s1_agent:rdata_fifo_sink_data
	wire         avalon_st_adapter_out_0_ready;                                                               // Expansion_JP2_s1_agent:rdata_fifo_sink_ready -> avalon_st_adapter:out_0_ready
	wire   [0:0] avalon_st_adapter_out_0_error;                                                               // avalon_st_adapter:out_0_error -> Expansion_JP2_s1_agent:rdata_fifo_sink_error

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (4),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (4),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (0),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (1),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (0),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) video_in_subsystem_top_io_gpi2_streamin_translator (
		.clk                    (System_PLL_sys_clk_clk),                                                                     //                       clk.clk
		.reset                  (Expansion_JP2_reset_reset_bridge_in_reset_reset),                                            //                     reset.reset
		.uav_address            (video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (Video_In_Subsystem_top_io_gpi2_streamin_address),                                            //      avalon_anti_master_0.address
		.av_chipselect          (Video_In_Subsystem_top_io_gpi2_streamin_chipselect),                                         //                          .chipselect
		.av_read                (Video_In_Subsystem_top_io_gpi2_streamin_read),                                               //                          .read
		.av_readdata            (Video_In_Subsystem_top_io_gpi2_streamin_readdata),                                           //                          .readdata
		.av_waitrequest         (),                                                                                           //               (terminated)
		.av_burstcount          (1'b1),                                                                                       //               (terminated)
		.av_byteenable          (4'b1111),                                                                                    //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                                       //               (terminated)
		.av_begintransfer       (1'b0),                                                                                       //               (terminated)
		.av_readdatavalid       (),                                                                                           //               (terminated)
		.av_write               (1'b0),                                                                                       //               (terminated)
		.av_writedata           (32'b00000000000000000000000000000000),                                                       //               (terminated)
		.av_lock                (1'b0),                                                                                       //               (terminated)
		.av_debugaccess         (1'b0),                                                                                       //               (terminated)
		.uav_clken              (),                                                                                           //               (terminated)
		.av_clken               (1'b1),                                                                                       //               (terminated)
		.uav_response           (2'b00),                                                                                      //               (terminated)
		.av_response            (),                                                                                           //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                                       //               (terminated)
		.av_writeresponsevalid  ()                                                                                            //               (terminated)
	);

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (4),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (4),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (0),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (1),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (0),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) video_in_subsystem_top_io_gpo2_streamout_translator (
		.clk                    (System_PLL_sys_clk_clk),                                                                      //                       clk.clk
		.reset                  (Expansion_JP2_reset_reset_bridge_in_reset_reset),                                             //                     reset.reset
		.uav_address            (video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (Video_In_Subsystem_top_io_gpo2_streamout_address),                                            //      avalon_anti_master_0.address
		.av_chipselect          (Video_In_Subsystem_top_io_gpo2_streamout_chipselect),                                         //                          .chipselect
		.av_write               (Video_In_Subsystem_top_io_gpo2_streamout_write),                                              //                          .write
		.av_writedata           (Video_In_Subsystem_top_io_gpo2_streamout_writedata),                                          //                          .writedata
		.av_waitrequest         (),                                                                                            //               (terminated)
		.av_burstcount          (1'b1),                                                                                        //               (terminated)
		.av_byteenable          (4'b1111),                                                                                     //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                                        //               (terminated)
		.av_begintransfer       (1'b0),                                                                                        //               (terminated)
		.av_read                (1'b0),                                                                                        //               (terminated)
		.av_readdata            (),                                                                                            //               (terminated)
		.av_readdatavalid       (),                                                                                            //               (terminated)
		.av_lock                (1'b0),                                                                                        //               (terminated)
		.av_debugaccess         (1'b0),                                                                                        //               (terminated)
		.uav_clken              (),                                                                                            //               (terminated)
		.av_clken               (1'b1),                                                                                        //               (terminated)
		.uav_response           (2'b00),                                                                                       //               (terminated)
		.av_response            (),                                                                                            //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                                        //               (terminated)
		.av_writeresponsevalid  ()                                                                                             //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (2),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (1),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (4),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) expansion_jp2_s1_translator (
		.clk                    (System_PLL_sys_clk_clk),                          //                      clk.clk
		.reset                  (Expansion_JP2_reset_reset_bridge_in_reset_reset), //                    reset.reset
		.uav_address            (expansion_jp2_s1_agent_m0_address),               // avalon_universal_slave_0.address
		.uav_burstcount         (expansion_jp2_s1_agent_m0_burstcount),            //                         .burstcount
		.uav_read               (expansion_jp2_s1_agent_m0_read),                  //                         .read
		.uav_write              (expansion_jp2_s1_agent_m0_write),                 //                         .write
		.uav_waitrequest        (expansion_jp2_s1_agent_m0_waitrequest),           //                         .waitrequest
		.uav_readdatavalid      (expansion_jp2_s1_agent_m0_readdatavalid),         //                         .readdatavalid
		.uav_byteenable         (expansion_jp2_s1_agent_m0_byteenable),            //                         .byteenable
		.uav_readdata           (expansion_jp2_s1_agent_m0_readdata),              //                         .readdata
		.uav_writedata          (expansion_jp2_s1_agent_m0_writedata),             //                         .writedata
		.uav_lock               (expansion_jp2_s1_agent_m0_lock),                  //                         .lock
		.uav_debugaccess        (expansion_jp2_s1_agent_m0_debugaccess),           //                         .debugaccess
		.av_address             (Expansion_JP2_s1_address),                        //      avalon_anti_slave_0.address
		.av_write               (Expansion_JP2_s1_write),                          //                         .write
		.av_readdata            (Expansion_JP2_s1_readdata),                       //                         .readdata
		.av_writedata           (Expansion_JP2_s1_writedata),                      //                         .writedata
		.av_chipselect          (Expansion_JP2_s1_chipselect),                     //                         .chipselect
		.av_read                (),                                                //              (terminated)
		.av_begintransfer       (),                                                //              (terminated)
		.av_beginbursttransfer  (),                                                //              (terminated)
		.av_burstcount          (),                                                //              (terminated)
		.av_byteenable          (),                                                //              (terminated)
		.av_readdatavalid       (1'b0),                                            //              (terminated)
		.av_waitrequest         (1'b0),                                            //              (terminated)
		.av_writebyteenable     (),                                                //              (terminated)
		.av_lock                (),                                                //              (terminated)
		.av_clken               (),                                                //              (terminated)
		.uav_clken              (1'b0),                                            //              (terminated)
		.av_debugaccess         (),                                                //              (terminated)
		.av_outputenable        (),                                                //              (terminated)
		.uav_response           (),                                                //              (terminated)
		.av_response            (2'b00),                                           //              (terminated)
		.uav_writeresponsevalid (),                                                //              (terminated)
		.av_writeresponsevalid  (1'b0)                                             //              (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_ORI_BURST_SIZE_H      (73),
		.PKT_ORI_BURST_SIZE_L      (71),
		.PKT_RESPONSE_STATUS_H     (70),
		.PKT_RESPONSE_STATUS_L     (69),
		.PKT_QOS_H                 (58),
		.PKT_QOS_L                 (58),
		.PKT_DATA_SIDEBAND_H       (56),
		.PKT_DATA_SIDEBAND_L       (56),
		.PKT_ADDR_SIDEBAND_H       (55),
		.PKT_ADDR_SIDEBAND_L       (55),
		.PKT_BURST_TYPE_H          (54),
		.PKT_BURST_TYPE_L          (53),
		.PKT_CACHE_H               (68),
		.PKT_CACHE_L               (65),
		.PKT_THREAD_ID_H           (61),
		.PKT_THREAD_ID_L           (61),
		.PKT_BURST_SIZE_H          (52),
		.PKT_BURST_SIZE_L          (50),
		.PKT_TRANS_EXCLUSIVE       (45),
		.PKT_TRANS_LOCK            (44),
		.PKT_BEGIN_BURST           (57),
		.PKT_PROTECTION_H          (64),
		.PKT_PROTECTION_L          (62),
		.PKT_BURSTWRAP_H           (49),
		.PKT_BURSTWRAP_L           (49),
		.PKT_BYTE_CNT_H            (48),
		.PKT_BYTE_CNT_L            (46),
		.PKT_ADDR_H                (39),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (40),
		.PKT_TRANS_POSTED          (41),
		.PKT_TRANS_WRITE           (42),
		.PKT_TRANS_READ            (43),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (59),
		.PKT_SRC_ID_L              (59),
		.PKT_DEST_ID_H             (60),
		.PKT_DEST_ID_L             (60),
		.ST_DATA_W                 (74),
		.ST_CHANNEL_W              (2),
		.AV_BURSTCOUNT_W           (3),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) video_in_subsystem_top_io_gpi2_streamin_agent (
		.clk                   (System_PLL_sys_clk_clk),                                                                     //       clk.clk
		.reset                 (Expansion_JP2_reset_reset_bridge_in_reset_reset),                                            // clk_reset.reset
		.av_address            (video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_address),       //        av.address
		.av_write              (video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_write),         //          .write
		.av_read               (video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_read),          //          .read
		.av_writedata          (video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_writedata),     //          .writedata
		.av_readdata           (video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_readdata),      //          .readdata
		.av_waitrequest        (video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_waitrequest),   //          .waitrequest
		.av_readdatavalid      (video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_readdatavalid), //          .readdatavalid
		.av_byteenable         (video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_byteenable),    //          .byteenable
		.av_burstcount         (video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_burstcount),    //          .burstcount
		.av_debugaccess        (video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_debugaccess),   //          .debugaccess
		.av_lock               (video_in_subsystem_top_io_gpi2_streamin_translator_avalon_universal_master_0_lock),          //          .lock
		.cp_valid              (video_in_subsystem_top_io_gpi2_streamin_agent_cp_valid),                                     //        cp.valid
		.cp_data               (video_in_subsystem_top_io_gpi2_streamin_agent_cp_data),                                      //          .data
		.cp_startofpacket      (video_in_subsystem_top_io_gpi2_streamin_agent_cp_startofpacket),                             //          .startofpacket
		.cp_endofpacket        (video_in_subsystem_top_io_gpi2_streamin_agent_cp_endofpacket),                               //          .endofpacket
		.cp_ready              (video_in_subsystem_top_io_gpi2_streamin_agent_cp_ready),                                     //          .ready
		.rp_valid              (rsp_mux_src_valid),                                                                          //        rp.valid
		.rp_data               (rsp_mux_src_data),                                                                           //          .data
		.rp_channel            (rsp_mux_src_channel),                                                                        //          .channel
		.rp_startofpacket      (rsp_mux_src_startofpacket),                                                                  //          .startofpacket
		.rp_endofpacket        (rsp_mux_src_endofpacket),                                                                    //          .endofpacket
		.rp_ready              (rsp_mux_src_ready),                                                                          //          .ready
		.av_response           (),                                                                                           // (terminated)
		.av_writeresponsevalid ()                                                                                            // (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_ORI_BURST_SIZE_H      (73),
		.PKT_ORI_BURST_SIZE_L      (71),
		.PKT_RESPONSE_STATUS_H     (70),
		.PKT_RESPONSE_STATUS_L     (69),
		.PKT_QOS_H                 (58),
		.PKT_QOS_L                 (58),
		.PKT_DATA_SIDEBAND_H       (56),
		.PKT_DATA_SIDEBAND_L       (56),
		.PKT_ADDR_SIDEBAND_H       (55),
		.PKT_ADDR_SIDEBAND_L       (55),
		.PKT_BURST_TYPE_H          (54),
		.PKT_BURST_TYPE_L          (53),
		.PKT_CACHE_H               (68),
		.PKT_CACHE_L               (65),
		.PKT_THREAD_ID_H           (61),
		.PKT_THREAD_ID_L           (61),
		.PKT_BURST_SIZE_H          (52),
		.PKT_BURST_SIZE_L          (50),
		.PKT_TRANS_EXCLUSIVE       (45),
		.PKT_TRANS_LOCK            (44),
		.PKT_BEGIN_BURST           (57),
		.PKT_PROTECTION_H          (64),
		.PKT_PROTECTION_L          (62),
		.PKT_BURSTWRAP_H           (49),
		.PKT_BURSTWRAP_L           (49),
		.PKT_BYTE_CNT_H            (48),
		.PKT_BYTE_CNT_L            (46),
		.PKT_ADDR_H                (39),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (40),
		.PKT_TRANS_POSTED          (41),
		.PKT_TRANS_WRITE           (42),
		.PKT_TRANS_READ            (43),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (59),
		.PKT_SRC_ID_L              (59),
		.PKT_DEST_ID_H             (60),
		.PKT_DEST_ID_L             (60),
		.ST_DATA_W                 (74),
		.ST_CHANNEL_W              (2),
		.AV_BURSTCOUNT_W           (3),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (1),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) video_in_subsystem_top_io_gpo2_streamout_agent (
		.clk                   (System_PLL_sys_clk_clk),                                                                      //       clk.clk
		.reset                 (Expansion_JP2_reset_reset_bridge_in_reset_reset),                                             // clk_reset.reset
		.av_address            (video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_address),       //        av.address
		.av_write              (video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_write),         //          .write
		.av_read               (video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_read),          //          .read
		.av_writedata          (video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_writedata),     //          .writedata
		.av_readdata           (video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_readdata),      //          .readdata
		.av_waitrequest        (video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_waitrequest),   //          .waitrequest
		.av_readdatavalid      (video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_readdatavalid), //          .readdatavalid
		.av_byteenable         (video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_byteenable),    //          .byteenable
		.av_burstcount         (video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_burstcount),    //          .burstcount
		.av_debugaccess        (video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_debugaccess),   //          .debugaccess
		.av_lock               (video_in_subsystem_top_io_gpo2_streamout_translator_avalon_universal_master_0_lock),          //          .lock
		.cp_valid              (video_in_subsystem_top_io_gpo2_streamout_agent_cp_valid),                                     //        cp.valid
		.cp_data               (video_in_subsystem_top_io_gpo2_streamout_agent_cp_data),                                      //          .data
		.cp_startofpacket      (video_in_subsystem_top_io_gpo2_streamout_agent_cp_startofpacket),                             //          .startofpacket
		.cp_endofpacket        (video_in_subsystem_top_io_gpo2_streamout_agent_cp_endofpacket),                               //          .endofpacket
		.cp_ready              (video_in_subsystem_top_io_gpo2_streamout_agent_cp_ready),                                     //          .ready
		.rp_valid              (rsp_mux_001_src_valid),                                                                       //        rp.valid
		.rp_data               (rsp_mux_001_src_data),                                                                        //          .data
		.rp_channel            (rsp_mux_001_src_channel),                                                                     //          .channel
		.rp_startofpacket      (rsp_mux_001_src_startofpacket),                                                               //          .startofpacket
		.rp_endofpacket        (rsp_mux_001_src_endofpacket),                                                                 //          .endofpacket
		.rp_ready              (rsp_mux_001_src_ready),                                                                       //          .ready
		.av_response           (),                                                                                            // (terminated)
		.av_writeresponsevalid ()                                                                                             // (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (73),
		.PKT_ORI_BURST_SIZE_L      (71),
		.PKT_RESPONSE_STATUS_H     (70),
		.PKT_RESPONSE_STATUS_L     (69),
		.PKT_BURST_SIZE_H          (52),
		.PKT_BURST_SIZE_L          (50),
		.PKT_TRANS_LOCK            (44),
		.PKT_BEGIN_BURST           (57),
		.PKT_PROTECTION_H          (64),
		.PKT_PROTECTION_L          (62),
		.PKT_BURSTWRAP_H           (49),
		.PKT_BURSTWRAP_L           (49),
		.PKT_BYTE_CNT_H            (48),
		.PKT_BYTE_CNT_L            (46),
		.PKT_ADDR_H                (39),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (40),
		.PKT_TRANS_POSTED          (41),
		.PKT_TRANS_WRITE           (42),
		.PKT_TRANS_READ            (43),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (59),
		.PKT_SRC_ID_L              (59),
		.PKT_DEST_ID_H             (60),
		.PKT_DEST_ID_L             (60),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (2),
		.ST_DATA_W                 (74),
		.AVS_BURSTCOUNT_W          (3),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) expansion_jp2_s1_agent (
		.clk                     (System_PLL_sys_clk_clk),                            //             clk.clk
		.reset                   (Expansion_JP2_reset_reset_bridge_in_reset_reset),   //       clk_reset.reset
		.m0_address              (expansion_jp2_s1_agent_m0_address),                 //              m0.address
		.m0_burstcount           (expansion_jp2_s1_agent_m0_burstcount),              //                .burstcount
		.m0_byteenable           (expansion_jp2_s1_agent_m0_byteenable),              //                .byteenable
		.m0_debugaccess          (expansion_jp2_s1_agent_m0_debugaccess),             //                .debugaccess
		.m0_lock                 (expansion_jp2_s1_agent_m0_lock),                    //                .lock
		.m0_readdata             (expansion_jp2_s1_agent_m0_readdata),                //                .readdata
		.m0_readdatavalid        (expansion_jp2_s1_agent_m0_readdatavalid),           //                .readdatavalid
		.m0_read                 (expansion_jp2_s1_agent_m0_read),                    //                .read
		.m0_waitrequest          (expansion_jp2_s1_agent_m0_waitrequest),             //                .waitrequest
		.m0_writedata            (expansion_jp2_s1_agent_m0_writedata),               //                .writedata
		.m0_write                (expansion_jp2_s1_agent_m0_write),                   //                .write
		.rp_endofpacket          (expansion_jp2_s1_agent_rp_endofpacket),             //              rp.endofpacket
		.rp_ready                (expansion_jp2_s1_agent_rp_ready),                   //                .ready
		.rp_valid                (expansion_jp2_s1_agent_rp_valid),                   //                .valid
		.rp_data                 (expansion_jp2_s1_agent_rp_data),                    //                .data
		.rp_startofpacket        (expansion_jp2_s1_agent_rp_startofpacket),           //                .startofpacket
		.cp_ready                (cmd_mux_src_ready),                                 //              cp.ready
		.cp_valid                (cmd_mux_src_valid),                                 //                .valid
		.cp_data                 (cmd_mux_src_data),                                  //                .data
		.cp_startofpacket        (cmd_mux_src_startofpacket),                         //                .startofpacket
		.cp_endofpacket          (cmd_mux_src_endofpacket),                           //                .endofpacket
		.cp_channel              (cmd_mux_src_channel),                               //                .channel
		.rf_sink_ready           (expansion_jp2_s1_agent_rsp_fifo_out_ready),         //         rf_sink.ready
		.rf_sink_valid           (expansion_jp2_s1_agent_rsp_fifo_out_valid),         //                .valid
		.rf_sink_startofpacket   (expansion_jp2_s1_agent_rsp_fifo_out_startofpacket), //                .startofpacket
		.rf_sink_endofpacket     (expansion_jp2_s1_agent_rsp_fifo_out_endofpacket),   //                .endofpacket
		.rf_sink_data            (expansion_jp2_s1_agent_rsp_fifo_out_data),          //                .data
		.rf_source_ready         (expansion_jp2_s1_agent_rf_source_ready),            //       rf_source.ready
		.rf_source_valid         (expansion_jp2_s1_agent_rf_source_valid),            //                .valid
		.rf_source_startofpacket (expansion_jp2_s1_agent_rf_source_startofpacket),    //                .startofpacket
		.rf_source_endofpacket   (expansion_jp2_s1_agent_rf_source_endofpacket),      //                .endofpacket
		.rf_source_data          (expansion_jp2_s1_agent_rf_source_data),             //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_out_0_ready),                     // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_out_0_valid),                     //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_out_0_data),                      //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_out_0_error),                     //                .error
		.rdata_fifo_src_ready    (expansion_jp2_s1_agent_rdata_fifo_src_ready),       //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (expansion_jp2_s1_agent_rdata_fifo_src_valid),       //                .valid
		.rdata_fifo_src_data     (expansion_jp2_s1_agent_rdata_fifo_src_data),        //                .data
		.m0_response             (2'b00),                                             //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                               //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (75),
		.FIFO_DEPTH          (2),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) expansion_jp2_s1_agent_rsp_fifo (
		.clk               (System_PLL_sys_clk_clk),                            //       clk.clk
		.reset             (Expansion_JP2_reset_reset_bridge_in_reset_reset),   // clk_reset.reset
		.in_data           (expansion_jp2_s1_agent_rf_source_data),             //        in.data
		.in_valid          (expansion_jp2_s1_agent_rf_source_valid),            //          .valid
		.in_ready          (expansion_jp2_s1_agent_rf_source_ready),            //          .ready
		.in_startofpacket  (expansion_jp2_s1_agent_rf_source_startofpacket),    //          .startofpacket
		.in_endofpacket    (expansion_jp2_s1_agent_rf_source_endofpacket),      //          .endofpacket
		.out_data          (expansion_jp2_s1_agent_rsp_fifo_out_data),          //       out.data
		.out_valid         (expansion_jp2_s1_agent_rsp_fifo_out_valid),         //          .valid
		.out_ready         (expansion_jp2_s1_agent_rsp_fifo_out_ready),         //          .ready
		.out_startofpacket (expansion_jp2_s1_agent_rsp_fifo_out_startofpacket), //          .startofpacket
		.out_endofpacket   (expansion_jp2_s1_agent_rsp_fifo_out_endofpacket),   //          .endofpacket
		.csr_address       (2'b00),                                             // (terminated)
		.csr_read          (1'b0),                                              // (terminated)
		.csr_write         (1'b0),                                              // (terminated)
		.csr_readdata      (),                                                  // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),              // (terminated)
		.almost_full_data  (),                                                  // (terminated)
		.almost_empty_data (),                                                  // (terminated)
		.in_empty          (1'b0),                                              // (terminated)
		.out_empty         (),                                                  // (terminated)
		.in_error          (1'b0),                                              // (terminated)
		.out_error         (),                                                  // (terminated)
		.in_channel        (1'b0),                                              // (terminated)
		.out_channel       ()                                                   // (terminated)
	);

	Computer_System_mm_interconnect_4_router router (
		.sink_ready         (video_in_subsystem_top_io_gpi2_streamin_agent_cp_ready),         //      sink.ready
		.sink_valid         (video_in_subsystem_top_io_gpi2_streamin_agent_cp_valid),         //          .valid
		.sink_data          (video_in_subsystem_top_io_gpi2_streamin_agent_cp_data),          //          .data
		.sink_startofpacket (video_in_subsystem_top_io_gpi2_streamin_agent_cp_startofpacket), //          .startofpacket
		.sink_endofpacket   (video_in_subsystem_top_io_gpi2_streamin_agent_cp_endofpacket),   //          .endofpacket
		.clk                (System_PLL_sys_clk_clk),                                         //       clk.clk
		.reset              (Expansion_JP2_reset_reset_bridge_in_reset_reset),                // clk_reset.reset
		.src_ready          (router_src_ready),                                               //       src.ready
		.src_valid          (router_src_valid),                                               //          .valid
		.src_data           (router_src_data),                                                //          .data
		.src_channel        (router_src_channel),                                             //          .channel
		.src_startofpacket  (router_src_startofpacket),                                       //          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                                          //          .endofpacket
	);

	Computer_System_mm_interconnect_4_router router_001 (
		.sink_ready         (video_in_subsystem_top_io_gpo2_streamout_agent_cp_ready),         //      sink.ready
		.sink_valid         (video_in_subsystem_top_io_gpo2_streamout_agent_cp_valid),         //          .valid
		.sink_data          (video_in_subsystem_top_io_gpo2_streamout_agent_cp_data),          //          .data
		.sink_startofpacket (video_in_subsystem_top_io_gpo2_streamout_agent_cp_startofpacket), //          .startofpacket
		.sink_endofpacket   (video_in_subsystem_top_io_gpo2_streamout_agent_cp_endofpacket),   //          .endofpacket
		.clk                (System_PLL_sys_clk_clk),                                          //       clk.clk
		.reset              (Expansion_JP2_reset_reset_bridge_in_reset_reset),                 // clk_reset.reset
		.src_ready          (router_001_src_ready),                                            //       src.ready
		.src_valid          (router_001_src_valid),                                            //          .valid
		.src_data           (router_001_src_data),                                             //          .data
		.src_channel        (router_001_src_channel),                                          //          .channel
		.src_startofpacket  (router_001_src_startofpacket),                                    //          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                                       //          .endofpacket
	);

	Computer_System_mm_interconnect_4_router_002 router_002 (
		.sink_ready         (expansion_jp2_s1_agent_rp_ready),                 //      sink.ready
		.sink_valid         (expansion_jp2_s1_agent_rp_valid),                 //          .valid
		.sink_data          (expansion_jp2_s1_agent_rp_data),                  //          .data
		.sink_startofpacket (expansion_jp2_s1_agent_rp_startofpacket),         //          .startofpacket
		.sink_endofpacket   (expansion_jp2_s1_agent_rp_endofpacket),           //          .endofpacket
		.clk                (System_PLL_sys_clk_clk),                          //       clk.clk
		.reset              (Expansion_JP2_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_002_src_ready),                            //       src.ready
		.src_valid          (router_002_src_valid),                            //          .valid
		.src_data           (router_002_src_data),                             //          .data
		.src_channel        (router_002_src_channel),                          //          .channel
		.src_startofpacket  (router_002_src_startofpacket),                    //          .startofpacket
		.src_endofpacket    (router_002_src_endofpacket)                       //          .endofpacket
	);

	Computer_System_mm_interconnect_4_cmd_demux cmd_demux (
		.clk                (System_PLL_sys_clk_clk),                          //       clk.clk
		.reset              (Expansion_JP2_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_src_ready),                                //      sink.ready
		.sink_channel       (router_src_channel),                              //          .channel
		.sink_data          (router_src_data),                                 //          .data
		.sink_startofpacket (router_src_startofpacket),                        //          .startofpacket
		.sink_endofpacket   (router_src_endofpacket),                          //          .endofpacket
		.sink_valid         (router_src_valid),                                //          .valid
		.src0_ready         (cmd_demux_src0_ready),                            //      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                            //          .valid
		.src0_data          (cmd_demux_src0_data),                             //          .data
		.src0_channel       (cmd_demux_src0_channel),                          //          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),                    //          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket)                       //          .endofpacket
	);

	Computer_System_mm_interconnect_4_cmd_demux cmd_demux_001 (
		.clk                (System_PLL_sys_clk_clk),                          //       clk.clk
		.reset              (Expansion_JP2_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_001_src_ready),                            //      sink.ready
		.sink_channel       (router_001_src_channel),                          //          .channel
		.sink_data          (router_001_src_data),                             //          .data
		.sink_startofpacket (router_001_src_startofpacket),                    //          .startofpacket
		.sink_endofpacket   (router_001_src_endofpacket),                      //          .endofpacket
		.sink_valid         (router_001_src_valid),                            //          .valid
		.src0_ready         (cmd_demux_001_src0_ready),                        //      src0.ready
		.src0_valid         (cmd_demux_001_src0_valid),                        //          .valid
		.src0_data          (cmd_demux_001_src0_data),                         //          .data
		.src0_channel       (cmd_demux_001_src0_channel),                      //          .channel
		.src0_startofpacket (cmd_demux_001_src0_startofpacket),                //          .startofpacket
		.src0_endofpacket   (cmd_demux_001_src0_endofpacket)                   //          .endofpacket
	);

	Computer_System_mm_interconnect_4_cmd_mux cmd_mux (
		.clk                 (System_PLL_sys_clk_clk),                          //       clk.clk
		.reset               (Expansion_JP2_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                               //       src.ready
		.src_valid           (cmd_mux_src_valid),                               //          .valid
		.src_data            (cmd_mux_src_data),                                //          .data
		.src_channel         (cmd_mux_src_channel),                             //          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                       //          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                         //          .endofpacket
		.sink0_ready         (cmd_demux_src0_ready),                            //     sink0.ready
		.sink0_valid         (cmd_demux_src0_valid),                            //          .valid
		.sink0_channel       (cmd_demux_src0_channel),                          //          .channel
		.sink0_data          (cmd_demux_src0_data),                             //          .data
		.sink0_startofpacket (cmd_demux_src0_startofpacket),                    //          .startofpacket
		.sink0_endofpacket   (cmd_demux_src0_endofpacket),                      //          .endofpacket
		.sink1_ready         (cmd_demux_001_src0_ready),                        //     sink1.ready
		.sink1_valid         (cmd_demux_001_src0_valid),                        //          .valid
		.sink1_channel       (cmd_demux_001_src0_channel),                      //          .channel
		.sink1_data          (cmd_demux_001_src0_data),                         //          .data
		.sink1_startofpacket (cmd_demux_001_src0_startofpacket),                //          .startofpacket
		.sink1_endofpacket   (cmd_demux_001_src0_endofpacket)                   //          .endofpacket
	);

	Computer_System_mm_interconnect_4_rsp_demux rsp_demux (
		.clk                (System_PLL_sys_clk_clk),                          //       clk.clk
		.reset              (Expansion_JP2_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_002_src_ready),                            //      sink.ready
		.sink_channel       (router_002_src_channel),                          //          .channel
		.sink_data          (router_002_src_data),                             //          .data
		.sink_startofpacket (router_002_src_startofpacket),                    //          .startofpacket
		.sink_endofpacket   (router_002_src_endofpacket),                      //          .endofpacket
		.sink_valid         (router_002_src_valid),                            //          .valid
		.src0_ready         (rsp_demux_src0_ready),                            //      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                            //          .valid
		.src0_data          (rsp_demux_src0_data),                             //          .data
		.src0_channel       (rsp_demux_src0_channel),                          //          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                    //          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket),                      //          .endofpacket
		.src1_ready         (rsp_demux_src1_ready),                            //      src1.ready
		.src1_valid         (rsp_demux_src1_valid),                            //          .valid
		.src1_data          (rsp_demux_src1_data),                             //          .data
		.src1_channel       (rsp_demux_src1_channel),                          //          .channel
		.src1_startofpacket (rsp_demux_src1_startofpacket),                    //          .startofpacket
		.src1_endofpacket   (rsp_demux_src1_endofpacket)                       //          .endofpacket
	);

	Computer_System_mm_interconnect_4_rsp_mux rsp_mux (
		.clk                 (System_PLL_sys_clk_clk),                          //       clk.clk
		.reset               (Expansion_JP2_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                               //       src.ready
		.src_valid           (rsp_mux_src_valid),                               //          .valid
		.src_data            (rsp_mux_src_data),                                //          .data
		.src_channel         (rsp_mux_src_channel),                             //          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                       //          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                         //          .endofpacket
		.sink0_ready         (rsp_demux_src0_ready),                            //     sink0.ready
		.sink0_valid         (rsp_demux_src0_valid),                            //          .valid
		.sink0_channel       (rsp_demux_src0_channel),                          //          .channel
		.sink0_data          (rsp_demux_src0_data),                             //          .data
		.sink0_startofpacket (rsp_demux_src0_startofpacket),                    //          .startofpacket
		.sink0_endofpacket   (rsp_demux_src0_endofpacket)                       //          .endofpacket
	);

	Computer_System_mm_interconnect_4_rsp_mux rsp_mux_001 (
		.clk                 (System_PLL_sys_clk_clk),                          //       clk.clk
		.reset               (Expansion_JP2_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_001_src_ready),                           //       src.ready
		.src_valid           (rsp_mux_001_src_valid),                           //          .valid
		.src_data            (rsp_mux_001_src_data),                            //          .data
		.src_channel         (rsp_mux_001_src_channel),                         //          .channel
		.src_startofpacket   (rsp_mux_001_src_startofpacket),                   //          .startofpacket
		.src_endofpacket     (rsp_mux_001_src_endofpacket),                     //          .endofpacket
		.sink0_ready         (rsp_demux_src1_ready),                            //     sink0.ready
		.sink0_valid         (rsp_demux_src1_valid),                            //          .valid
		.sink0_channel       (rsp_demux_src1_channel),                          //          .channel
		.sink0_data          (rsp_demux_src1_data),                             //          .data
		.sink0_startofpacket (rsp_demux_src1_startofpacket),                    //          .startofpacket
		.sink0_endofpacket   (rsp_demux_src1_endofpacket)                       //          .endofpacket
	);

	Computer_System_mm_interconnect_0_avalon_st_adapter #(
		.inBitsPerSymbol (34),
		.inUsePackets    (0),
		.inDataWidth     (34),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (34),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter (
		.in_clk_0_clk   (System_PLL_sys_clk_clk),                          // in_clk_0.clk
		.in_rst_0_reset (Expansion_JP2_reset_reset_bridge_in_reset_reset), // in_rst_0.reset
		.in_0_data      (expansion_jp2_s1_agent_rdata_fifo_src_data),      //     in_0.data
		.in_0_valid     (expansion_jp2_s1_agent_rdata_fifo_src_valid),     //         .valid
		.in_0_ready     (expansion_jp2_s1_agent_rdata_fifo_src_ready),     //         .ready
		.out_0_data     (avalon_st_adapter_out_0_data),                    //    out_0.data
		.out_0_valid    (avalon_st_adapter_out_0_valid),                   //         .valid
		.out_0_ready    (avalon_st_adapter_out_0_ready),                   //         .ready
		.out_0_error    (avalon_st_adapter_out_0_error)                    //         .error
	);

endmodule
